import React from "react";

export default function About() {
    return (
        <div style={{ padding: '20px' }}>
            <h2>About the App</h2>


            <p><strong>Real-Time Event Dashboard</strong> visualizes data in real time, showcasing interactions with a dynamic set of products.</p>
            <p>Event generator with spring boot that creates fake user interactions and publishes them.</p>
            <p>Published items aggregated to generate meaningful statistics using stream api. </p>
            <p>A Node.js application subscribes to these Kafka topics, consuming the aggregated messages. It then forwards this data to the frontend through a WebSocket connection. </p>
            <p>Simple frontend application displays logs of raw events and visualize some aggregated data with chart*?s(currently one, with plans for more)</p>

            <p><strong>Note:</strong> Since events are generated by Java Faker individually, some statistics might be unusual.(e.g product purchased more than it is viewed.)</p>
            <p><strong>Infrastructure:</strong> Services are hosted on Render.com, with Kafka server deployed on Upstash, prioritizing solutions that offer generous free tiers.</p>
        </div>
    );
}
